Document: gmcserver
Title: Debian gmcserver Manual
Author: <insert document author here>
Abstract: This manual describes what gmcserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gmcserver/gmcserver.sgml.gz

Format: postscript
Files: /usr/share/doc/gmcserver/gmcserver.ps.gz

Format: text
Files: /usr/share/doc/gmcserver/gmcserver.text.gz

Format: HTML
Index: /usr/share/doc/gmcserver/html/index.html
Files: /usr/share/doc/gmcserver/html/*.html
