name: Integration tests

on:
  push:
    branches:
      - '**'
      - '!deploy'
  pull_request:
    branches:
      - '**'
      - '!deploy'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Dependencies
      run: sudo apt-get update && sudo apt-get install npm && sudo npm install -g pnpm
    - name: Build with Maven
      run: mvn -B compile assembly:single --file pom.xml
      working-directory: gmcserver-server/
    - name: pnpm dependencies
      run: pnpm i
      working-directory: gmcserver-integration-tests/
    - run: cp gmcserver-integration-tests/server-config.properties gmcserver-server/config.properties
    - name: Run backend
      run: java -jar target/gmcserver*jar-with-dependencies.jar &
      working-directory: gmcserver-server/
    - name: Run tests
      run: pnpm test
      env:
        URL: http://localhost:8080/api/v1
        LOG_URL: http://localhost:8080
      working-directory: gmcserver-integration-tests/
