# This is a basic workflow to help you get started with Actions

name: Make debian

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'
      - '!deploy'
  pull_request:
    branches:
      - '**'
      - '!deploy'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get update && sudo apt-get install debhelper-compat maven npm && sudo npm install -g pnpm
    ########## BACKEND
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/setup-node@v3
      with:
        node-version: 16
      ########## BUILD
    - name: Build package
      run: dpkg-buildpackage -b

      ########## UPDLOAD
    - uses: actions/upload-artifact@v2
      with:
        name: gmcserver-debian-$GITHUB_REF-$GITHUB_SHA
        path: ~/**/*.deb
